import { StyleSheet } from 'react-native';

const MuyaoFont = require('./assets/fonts/Muyao-Softbrush.ttf');

export default styles = StyleSheet.create({
      muyaoTextStyle:{
        fontFamily: 'Muyao-Softbrush',
        fontSize: 20,
      },
      preview: {
        width: 335,
        height: 114,
        backgroundColor: "#F8F8F8",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 15,
      },
      previewText: {
        color: "#FFF",
        fontSize: 14,
        height: 40,
        lineHeight: 40,
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: "#69B2FF",
        width: 120,
        textAlign: "center",
        marginTop: 10,
      },
      container: {
        flex: 1,
        backgroundColor: '#F6E7D4',
      },
      draw: {
          flex: 1,
          backgroundColor: '#fff',
      },
      header: {
        height: 111,
        width: 1080,
        top: 20,
        backgroundColor: 'transparent',
        alignItems: 'center',
        zIndex: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
      },
      bookShelf: {
        top: 40,
        height: 455,
        backgroundColor: 'transparent',
        zIndex: 1,
      },
      book: {
        width: 401,
        height: 401,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
      },
      addButton:{
        zIndex: 1,
      },
      assiant:{
        zIndex: 1,
      },
      dora:{
        width: 1080,
        height: 70,
        backgroundColor: '#FFC602',
        zIndex: 0,
        position: 'absolute',
        bottom: 0,
      },
      bookItem: {
        width: 455,
        height: 455,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 0,
      },
      image: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        borderRadius: 8, 
        zIndex: 0,
      },
      imagebook: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        borderRadius: 8, 
        zIndex: 0,
        width: 560,
        height: 444,
      },
      imageshader: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        zIndex: 1,
      },
      robot: {
        // backgroundColor: 'green',
        position: 'absolute',
        bottom: 35,
        left: 36,
        height:140,
        width:140,
      },
      import: {
        position: 'absolute',
        bottom: 35,
        right: 36,
      },
      dataset: {
        position: 'absolute',
        bottom: 35,
        right: 190,
      },
      nextpage: {
        position: 'absolute',
        bottom: 35,
        right: 344,
      },
      back:{
        position: 'absolute',
        top: 50,
        left: 51,
      },
      InfoCont:{
        top:67, 
        left:85, 
        width:910, 
        height:429, 
        backgroundColor:'transparent',
        flexDirection: 'row',
      },
      left: {
        flex: 1,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
      },
      right: {
        flex: 1,
        backgroundColor: 'transparent',
        padding: 10,
      },
      boxstyle: {
        backgroundColor: '#F39F27',
        borderWidth: 5,
        borderColor: '#884F00',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 0,
        position: 'absolute',
      },
      boxstyleinner: {
        backgroundColor: '#FFDEB3',
        borderWidth: 5,
        borderColor: '#BAAFA2',
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 0,
        position: 'absolute',
      },
      messagebox: {
        position: 'absolute',
        height:140,
        width:400,
        bottom:0,
        left:140,
        zIndex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      messageboxinner: {
        position: 'absolute',
        height:140,
        width:380,
        borderRadius: 15,
        backgroundColor: '#FFDEB3',
        borderWidth: 3,
        borderColor: '#A0611E',
        borderStyle: 'dashed'
      },
      voicebutton:{
        backgroundColor:'transparent',
        width:40,
        height:40,
        left:328,
        bottom:0,
        position:'relative',
        borderRadius:10,
        justifyContent: 'center',
        alignItems: 'center'
      },
      colordict:{
        width:770,
        height:67,
        backgroundColor:'#FFC602',
        left:195,
        top:40,
        position:'absolute',
        borderRadius:15,
        borderColor:'#A0611E',
        borderWidth:2,
        borderStyle:'dashed',
        flexDirection:'row',
        justifyContent: 'center',
        alignItems: 'center'
      },
      preview: {
        width: 335,
        height: 114,
        backgroundColor: "green",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 15,
      },
  });